---
name: Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - image: 'ros:noetic'
            env:
              PYTHON_VERSION: 3
              ROS_DISTRO: noetic

    container: ${{ matrix.container }}

#     defaults:
#       run:
#         shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/${{ github.workspace }}
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1


      - name: Remove broken apt repos [Ubuntu]
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

      - name: Install ROS package dependencies
        run: |
          sudo apt update
          sudo apt install -y git
          sudo apt install -y python3-pip
          sudo apt install -y python$PYTHON_VERSION-osrf-pycommon
          sudo apt install -y python$PYTHON_VERSION-catkin-tools
          python$PYTHON_VERSION -m pip install --upgrade pip
          python3 -m pip install --upgrade pip

          
      - name: Additional dependencies
        run: |
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-bringup
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-description
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-gazebo
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-msgs
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-navigation
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-simulations
          sudo apt install -y ros-$ROS_DISTRO-turtlebot3-slam
          sudo apt install -y ros-$ROS_DISTRO-move-base
          sudo apt install -y ros-$ROS_DISTRO-move-base-msgs
          sudo apt install -y ros-$ROS_DISTRO-aruco-detect
          sudo apt install -y ros-$ROS_DISTRO-tf
          sudo apt install -y ros-$ROS_DISTRO-tf2-ros
          sudo apt install -y ros-$ROS_DISTRO-actionlib
          sudo apt install -y ros-$ROS_DISTRO-actionlib-msgs
          sudo apt install -y ros-$ROS_DISTRO-amcl
          sudo apt install -y ros-$ROS_DISTRO-map-server
          sudo apt install -y ros-$ROS_DISTRO-navigation
          sudo apt-get install -y ros-$ROS_DISTRO-gazebo-ros-pkgs ros-$ROS_DISTRO-gazebo-msgs
          sudo apt install -y libgazebo9 gazebo9-common gazebo9-plugin-base
          sudo apt-get install -y libgazebo9-dev
          sudo apt install -y ros-noetic-moveit

          source /opt/ros/noetic/setup.bash
          rospack profile
          
      - name: Create workspace
        run: |
          cd src
          wstool init
          cd ..
          rosdep update
          rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
          
      - name: Build workspace
        if: contains(matrix.container.image, 'melodic') || contains(matrix.container.image, 'noetic')
        run: |
          . /opt/ros/$ROS_DISTRO/setup.bash
          catkin build

      - name: Unit tests
        run: |
          sudo apt install -y lcov
          . /opt/ros/$ROS_DISTRO/setup.bash
          catkin config --cmake-args -DCMAKE_CXX_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_C_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-lgcov"
          catkin build
          catkin run_tests -i
          cat /__w/Wall-E/Wall-E/build/wall-e/test_results/wall-e/rostest-test_main_test.xml
          catkin_test_results

      - name: Configure Codecov
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/opt/*' '/usr/*' '*/devel/*' '*_test*' --output-file coverage.info
          lcov --list coverage.info
      
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
